pipeline:
  name: retail

includes:
  bronze: backend/bronze.yaml
  silver: backend/silver.yaml
  gold:   backend/gold.yaml

paths:
  bronze: "retail/data/bronze"
  silver: "retail/data/silver"
  gold:   "retail/data/gold"
  export: "retail/data/export"
