"""tests/test_scaffold.py — openmedallion.scaffold.templates.init_project.

No tests existed for the scaffold module before this file. Coverage here is
scoped to what changed: the generated README/notebook now document the RAG
accuracy add-ons (metadata/relationships/examples, `medallion query`) as an
optional next step. `medallion init` intentionally does NOT create
metadata.yaml/relationships.yaml/examples/ itself — those are generated by
their own `medallion metadata|relationships|examples generate` commands
against real silver/gold data, which doesn't exist yet at scaffold time.
"""
from __future__ import annotations

import json

from openmedallion.scaffold.templates import init_project


class TestInitProject:

    def test_creates_expected_structure(self, tmp_path):
        init_project("demo_proj", path_project=tmp_path)
        project_dir = tmp_path / "demo_proj"
        assert (project_dir / "main.yaml").exists()
        assert (project_dir / "backend" / "bronze.yaml").exists()
        assert (project_dir / "backend" / "silver.yaml").exists()
        assert (project_dir / "backend" / "gold.yaml").exists()
        assert (project_dir / "README.md").exists()
        assert (project_dir / "ipynb" / "walkthrough.ipynb").exists()
        assert (project_dir / "kestra_flow.yaml").exists()

    def test_aborts_if_project_already_exists(self, tmp_path, capsys):
        init_project("demo_proj", path_project=tmp_path)
        init_project("demo_proj", path_project=tmp_path)
        out = capsys.readouterr().out
        assert "already exists" in out

    def test_does_not_create_rag_config_files(self, tmp_path):
        # metadata.yaml/relationships.yaml/examples/ are generated later by
        # their own `medallion ... generate` commands against real silver
        # data — scaffolding blank versions at init time wouldn't be useful.
        init_project("demo_proj", path_project=tmp_path)
        project_dir = tmp_path / "demo_proj"
        assert not (project_dir / "metadata.yaml").exists()
        assert not (project_dir / "relationships.yaml").exists()
        assert not (project_dir / "examples").exists()

    def test_readme_documents_rag_workflow(self, tmp_path):
        init_project("demo_proj", path_project=tmp_path)
        readme = (tmp_path / "demo_proj" / "README.md").read_text()
        assert "Natural-Language Queries" in readme
        assert "medallion query demo_proj" in readme
        assert "medallion metadata generate      demo_proj" in readme
        assert "medallion relationships generate demo_proj" in readme
        assert "medallion examples generate      demo_proj" in readme

    def test_walkthrough_notebook_has_rag_step(self, tmp_path):
        init_project("demo_proj", path_project=tmp_path)
        nb = json.loads((tmp_path / "demo_proj" / "ipynb" / "walkthrough.ipynb").read_text())
        source = "\n".join("".join(cell["source"]) for cell in nb["cells"])
        assert "Step 6 — Natural-language queries" in source
        assert "medallion query demo_proj" in source
        assert "medallion examples approve  demo_proj" in source

    def test_walkthrough_notebook_is_valid_json(self, tmp_path):
        init_project("demo_proj", path_project=tmp_path)
        nb_path = tmp_path / "demo_proj" / "ipynb" / "walkthrough.ipynb"
        nb = json.loads(nb_path.read_text())
        assert nb["nbformat"] == 4
        assert len(nb["cells"]) > 0
