pipeline:
  name: ecommerce

includes:
  bronze: bronze.yaml
  silver: silver.yaml
  gold:   gold.yaml

paths:
  bronze: "./data/ecommerce/bronze"
  silver: "./data/ecommerce/silver"
  gold:   "./data/ecommerce/gold"
  export: "./data/ecommerce/export"
