pipeline:
  name: ecommerce

includes:
  bronze: backend/bronze.yaml
  silver: backend/silver.yaml
  gold:   backend/gold.yaml

paths:
  bronze: "data/bronze"
  silver: "data/silver"
  gold:   "data/gold"
  export: "data/export"
