pipeline:
  name: demo

includes:
  bronze: bronze.yaml
  silver: silver.yaml
  gold:   gold.yaml

paths:
  bronze: "./data/demo/bronze"
  silver: "./data/demo/silver"
  gold:   "./data/demo/gold"
  export: "./data/demo/export"
